language: java

before_install:
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export ANDROID_HOME=~/builds/abarisain/dmix/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - ls ~/builds/abarisain/dmix/android-sdk-linux
  - android update sdk --filter 1,5 --no-ui --force

script:
  - cd ./MPDroid
  - android project update -path .
  - ant clean
  - ant debug
